name: Aperture
version: 1.1.1
main: com.hadenwatne.aperture.Aperture
author: Cynicalvoe
api-version: 1.13
softdepend: [ProtocolLib]
commands:
  ap:
  aperture:
permissions:
  aperture.reload:
    default: op
  aperture.getcamera:
    default: op
  aperture.stream:
    default: true 
  aperture.stream.other:
    default: op
  aperture.share:
    default: true
  aperture.break:
    default: true
  aperture.break.other:
    default: op
  aperture.place:
    default: true
  aperture.bypasslimit:
    default: op
  aperture.camera.*:
    default: op
  aperture.player:
    children:
      aperture.stream: true
      aperture.share: true
      aperture.break: true
      aperture.place: true
  aperture.admin:
    children:
      aperture.break.other: true
      aperture.stream.other: true
      aperture.reload: true
      aperture.getcamera: true
      aperture.bypasslimit: true
      aperture.camera.*: true
      aperture.player: true